create_clock -name core_clk -period 10.000 [get_ports clk_i]
set_clock_uncertainty 0.100 [get_clocks core_clk]
set_input_delay 1.000 -clock core_clk [get_ports {enable_i data_i[*]}]
set_output_delay 1.000 -clock core_clk [get_ports data_o[*]]
set_false_path -from [get_ports rst_ni]
